import enum

class EvidenceLevel(str, enum.Enum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    HYPOTHESIZED = "HYPOTHESIZED"

class JourneyStage(str, enum.Enum):
    DISCOVERY = "DISCOVERY"
    BROWSING = "BROWSING"
    PRODUCT_CONSIDERATION = "PRODUCT_CONSIDERATION"
    SHORTLISTING = "SHORTLISTING"
    COMPARISON = "COMPARISON"
    WISHLIST = "WISHLIST"
    EVALUATION = "EVALUATION"
    PURCHASE = "PURCHASE"
    PURCHASE_POSTPONEMENT = "PURCHASE_POSTPONEMENT"
    ABANDONMENT = "ABANDONMENT"
    POST_PURCHASE = "POST_PURCHASE"

class TrendDirection(str, enum.Enum):
    INCREASING = "INCREASING"
    STABLE = "STABLE"
    DECREASING = "DECREASING"

class SourcePlatform(str, enum.Enum):
    PLAY_STORE = "PLAY_STORE"
    APP_STORE = "APP_STORE"
    REDDIT = "REDDIT"
    YOUTUBE = "YOUTUBE"
    PRODUCT_REVIEWS = "PRODUCT_REVIEWS"
    TWITTER = "TWITTER"
    INSTAGRAM = "INSTAGRAM"
    MOCK = "MOCK"
