"""Update schema

Revision ID: 3f7f0b01e12a
Revises: 85e404bdf617
Create Date: 2026-08-23 16:03:10.996767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f7f0b01e12a'
down_revision: Union[str, Sequence[str], None] = '85e404bdf617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_signal', sa.Column('signal_type', sa.String(length=50), nullable=True))
    op.add_column('ai_signal', sa.Column('summary', sa.String(length=255), nullable=True))
    op.add_column('ai_signal', sa.Column('evidence_quote', sa.Text(), nullable=True))
    op.add_column('ai_signal', sa.Column('extracted_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_ai_signal_category'), table_name='ai_signal')
    op.drop_index(op.f('idx_ai_signal_evidence'), table_name='ai_signal')
    op.drop_index(op.f('idx_ai_signal_journey_barrier'), table_name='ai_signal')
    op.create_index('idx_ai_signal_journey_type', 'ai_signal', ['journey_stage', 'signal_type'], unique=False)
    op.drop_column('ai_signal', 'subcategory')
    op.drop_column('ai_signal', 'analyzed_at')
    op.drop_column('ai_signal', 'user_type')
    op.drop_column('ai_signal', 'desired_outcome')
    op.drop_column('ai_signal', 'product')
    op.drop_column('ai_signal', 'barrier')
    op.drop_column('ai_signal', 'intent_level')
    op.drop_column('ai_signal', 'unmet_need')
    op.drop_column('ai_signal', 'decision_criteria')
    op.drop_column('ai_signal', 'purchase_outcome')
    op.drop_column('ai_signal', 'brand')
    op.drop_column('ai_signal', 'model_version')
    op.drop_column('ai_signal', 'category')
    op.drop_column('ai_signal', 'external_info_seeking')
    op.drop_column('ai_signal', 'category_familiarity')
    op.drop_column('ai_signal', 'price_band')
    op.drop_column('ai_signal', 'purchase_frequency')
    op.drop_column('ai_signal', 'uncertainty')
    op.drop_column('ai_signal', 'intent')
    op.drop_column('ai_signal', 'user_segment')
    op.drop_column('ai_signal', 'motivation')
    op.drop_column('ai_signal', 'product_attributes')
    op.drop_column('ai_signal', 'evidence_level')
    op.drop_column('ai_signal', 'competitor_mentions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_signal', sa.Column('competitor_mentions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('evidence_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('product_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('motivation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('user_segment', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('uncertainty', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('purchase_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('price_band', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('category_familiarity', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('external_info_seeking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('purchase_outcome', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('decision_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('unmet_need', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('intent_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('barrier', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('product', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('desired_outcome', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('user_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('analyzed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ai_signal', sa.Column('subcategory', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index('idx_ai_signal_journey_type', table_name='ai_signal')
    op.create_index(op.f('idx_ai_signal_journey_barrier'), 'ai_signal', ['journey_stage', 'barrier'], unique=False)
    op.create_index(op.f('idx_ai_signal_evidence'), 'ai_signal', ['evidence_level'], unique=False)
    op.create_index(op.f('idx_ai_signal_category'), 'ai_signal', ['category', 'subcategory'], unique=False)
    op.drop_column('ai_signal', 'extracted_at')
    op.drop_column('ai_signal', 'evidence_quote')
    op.drop_column('ai_signal', 'summary')
    op.drop_column('ai_signal', 'signal_type')
    # ### end Alembic commands ###
