"""initial_schema

Revision ID: 85e404bdf617
Revises: 
Create Date: 2026-08-19 12:55:05.529383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '85e404bdf617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('cohesion_score', sa.Float(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_theme', 'cluster', ['theme'], unique=False)
    op.create_table('data_source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_segment', sa.String(length=100), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('behavior', sa.Text(), nullable=True),
    sa.Column('barrier', sa.Text(), nullable=True),
    sa.Column('unmet_need', sa.Text(), nullable=True),
    sa.Column('potential_solution', sa.Text(), nullable=True),
    sa.Column('potential_business_impact', sa.Text(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('supporting_conversations', sa.Integer(), nullable=True),
    sa.Column('independent_sources', sa.Integer(), nullable=True),
    sa.Column('source_platforms', sqlite.JSON(), nullable=True),
    sa.Column('time_period', sa.String(length=100), nullable=True),
    sa.Column('supporting_evidence', sqlite.JSON(), nullable=True),
    sa.Column('contradictory_evidence', sqlite.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_opp_evidence_confidence', 'opportunity', ['evidence_level', 'confidence_level'], unique=False)
    op.create_table('pattern',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pattern_type', sa.String(length=50), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('segment_distribution', sqlite.JSON(), nullable=True),
    sa.Column('category_distribution', sqlite.JSON(), nullable=True),
    sa.Column('time_distribution', sqlite.JSON(), nullable=True),
    sa.Column('trend_direction', sa.String(length=50), nullable=True),
    sa.Column('strength_score', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_trend_strength', 'pattern', ['trend_direction', 'strength_score'], unique=False)
    op.create_table('feedback_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('source_date', sa.DateTime(), nullable=True),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('author_id_anonymized', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('idx_feedback_platform_date', 'feedback_item', ['source_platform', 'source_date'], unique=False)
    op.create_table('opportunity_score',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('reach', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('business_impact', sa.Float(), nullable=True),
    sa.Column('evidence_strength', sa.Float(), nullable=True),
    sa.Column('cross_source_consistency', sa.Float(), nullable=True),
    sa.Column('cross_segment_relevance', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('strategic_relevance', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('dimension_weights', sqlite.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id')
    )
    op.create_index('idx_opp_score_composite', 'opportunity_score', ['composite_score'], unique=False)
    op.create_table('ai_signal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_item_id', sa.String(length=36), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('journey_stage', sa.String(length=50), nullable=True),
    sa.Column('motivation', sa.String(length=255), nullable=True),
    sa.Column('uncertainty', sa.String(length=255), nullable=True),
    sa.Column('barrier', sa.String(length=255), nullable=True),
    sa.Column('decision_criteria', sqlite.JSON(), nullable=True),
    sa.Column('desired_outcome', sa.String(length=255), nullable=True),
    sa.Column('purchase_outcome', sa.String(length=100), nullable=True),
    sa.Column('external_info_seeking', sa.Boolean(), nullable=True),
    sa.Column('competitor_mentions', sqlite.JSON(), nullable=True),
    sa.Column('unmet_need', sa.String(length=255), nullable=True),
    sa.Column('opportunity_theme', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('price_band', sa.String(length=50), nullable=True),
    sa.Column('product_attributes', sqlite.JSON(), nullable=True),
    sa.Column('user_segment', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('purchase_frequency', sa.String(length=50), nullable=True),
    sa.Column('category_familiarity', sa.String(length=50), nullable=True),
    sa.Column('intent_level', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['feedback_item_id'], ['feedback_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_signal_category', 'ai_signal', ['category', 'subcategory'], unique=False)
    op.create_index('idx_ai_signal_evidence', 'ai_signal', ['evidence_level'], unique=False)
    op.create_index('idx_ai_signal_journey_barrier', 'ai_signal', ['journey_stage', 'barrier'], unique=False)
    op.create_table('cluster_membership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedback_item_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['feedback_item_id'], ['feedback_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_item_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_item_id'], ['feedback_item.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['pattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=True),
    sa.Column('feedback_item_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['feedback_item_id'], ['feedback_item.id'], ),
    sa.ForeignKeyConstraint(['pattern_id'], ['pattern.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern_evidence')
    op.drop_table('opportunity_evidence')
    op.drop_table('cluster_membership')
    op.drop_index('idx_ai_signal_journey_barrier', table_name='ai_signal')
    op.drop_index('idx_ai_signal_evidence', table_name='ai_signal')
    op.drop_index('idx_ai_signal_category', table_name='ai_signal')
    op.drop_table('ai_signal')
    op.drop_index('idx_opp_score_composite', table_name='opportunity_score')
    op.drop_table('opportunity_score')
    op.drop_index('idx_feedback_platform_date', table_name='feedback_item')
    op.drop_table('feedback_item')
    op.drop_index('idx_pattern_trend_strength', table_name='pattern')
    op.drop_table('pattern')
    op.drop_index('idx_opp_evidence_confidence', table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_table('data_source')
    op.drop_index('idx_cluster_theme', table_name='cluster')
    op.drop_table('cluster')
    # ### end Alembic commands ###
